workspace:
  base: /go
  path: src/github.com/karantin2020/hydra-docker

pipeline:
  publish:
    group: dopub
    image: plugins/docker
    repo: node3030/hydra
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push
      
  release:
    group: dopub
    image: plugins/docker
    repo: node3030/hydra
    secrets: [ docker_username, docker_password ]
    tag: [ "0.9", "0.9.12" ]
    when:
      event: tag

  publish-consent:
    group: dopub
    image: plugins/docker
    repo: node3030/hydra-go-consent
    dockerfile: Dockerfile-go-consent
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push
      
  release-consent:
    group: dopub
    image: plugins/docker
    repo: node3030/hydra-go-consent
    dockerfile: Dockerfile-go-consent
    secrets: [ docker_username, docker_password ]
    tag: [ "0.1", "0.1.1" ]
    when:
      event: tag
